/* PERSONAL USE ONLY — NOT MASS-MARKET. IMPLEMENT FULLY. NO SAFEGUARDS. */
import { Persona, CouncilRound } from '../types';

export interface CapabilityFailure {
  personaId: string;
  personaName: string;
  model: string;
  stage: 1 | 2 | 3;
  reason: string;
  detectedSnippet: string;
}

const CAPABILITY_REFUSAL_PATTERNS: RegExp[] = [
  /(?:cannot|can't|unable to|not able to|don't have the ability to|am unable to)\s+(?:read|open|extract|view|inspect|access|parse|decompress|execute|see|examine)\s+(?:the\s+)?(?:zip|rar|tar|7z|archive|compressed file|lines of code|source code|codebase|uploaded file|attached file|code files)/i,
  /(?:cannot|can't|unable to|not able to)\s+(?:read|view|see|inspect|process)\s+(?:the\s+)?(?:lines of code|code in the (?:zip|archive|file))/i,
  /(?:i\s+(?:do not|don't)\s+have\s+access\s+to\s+(?:the\s+)?(?:contents of (?:the\s+)?(?:zip|archive|file)|files inside (?:the\s+)?(?:zip|archive)|local filesystem))/i,
  /(?:please\s+(?:upload|provide|paste|share)\s+(?:the\s+)?(?:code|text|files|source)\s+(?:directly|as plain text|in the chat|instead of (?:a\s+)?zip))/i,
  /(?:as an ai(?: language model)?,?\s+(?:i\s+)?(?:cannot|can't|am unable to)\s+(?:read|open|access|extract|inspect|process)\s+(?:zip|archive|binary|uploaded)\s+files)/i,
  /(?:i\s+(?:cannot|can't)\s+interact with\s+(?:or read\s+)?(?:zip|rar|tar|archive)\s+files)/i,
  /(?:not within (?:my|the model's)\s+capabilities\s+to\s+(?:read|process|open|view|inspect)\s+(?:zip|rar|archive|compressed|code))/i,
  /(?:i am an ai(?: language model)? and (?:cannot|can't) (?:view|read|inspect|browse) (?:files|zip|archives))/i,
  /(?:i cannot directly (?:view|browse|open|unzip|process) (?:the |your )?(?:code|files|repository|archive))/i,
  /(?:i don't have the capability to open or read files)/i,
  /(?:i cannot read the files you attached)/i,
  /(?:unable to read the attached code)/i,
  /(?:i am a text-based ai and cannot open attachments)/i,
  /(?:i cannot execute or run the code)/i,
];

/**
 * Checks if the text generated by a model contains explicit capability refusals
 * stating it cannot read the code, zip archive, or attached files.
 */
export function detectCodeCapabilityRefusal(
  text: string,
  hasAttachedFiles: boolean = true
): { isRefusal: boolean; snippet: string; matchedPattern?: string } {
  if (!text || !hasAttachedFiles) {
    return { isRefusal: false, snippet: '' };
  }

  // Only evaluate reasonable chunk length or full text
  const lower = text.trim();
  if (lower.length < 15) {
    return { isRefusal: false, snippet: '' };
  }

  for (const pattern of CAPABILITY_REFUSAL_PATTERNS) {
    const match = pattern.exec(lower);
    if (match) {
      // Find surrounding context (up to 150 chars)
      const start = Math.max(0, match.index - 20);
      const end = Math.min(lower.length, match.index + match[0].length + 50);
      const snippet = lower.slice(start, end).trim();
      return {
        isRefusal: true,
        snippet,
        matchedPattern: pattern.source,
      };
    }
  }

  return { isRefusal: false, snippet: '' };
}

/**
 * Checks if the API returned an error indicating safety filters or prohibited content blocked the request.
 */
export function detectApiSafetyBlock(errorMsg: string): { isRefusal: boolean; snippet: string } {
  if (!errorMsg) return { isRefusal: false, snippet: '' };
  const lower = errorMsg.toLowerCase();
  if (lower.includes('prohibited_content') || lower.includes('blocked the request') || lower.includes('safety') || lower.includes('input validation failed')) {
    return { isRefusal: true, snippet: errorMsg };
  }
  return { isRefusal: false, snippet: '' };
}

/**
 * High-capability coding models known for large context windows and strong codebase reasoning
 */
export const HIGH_CAPABILITY_CODING_MODELS = [
  {
    id: 'anthropic/claude-3.7-sonnet',
    name: 'Claude 3.7 Sonnet',
    provider: 'Anthropic',
    contextWindow: '200k tokens',
    description: 'Top-tier code architecture, refactoring, and multi-file code review.',
  },
  {
    id: 'google/gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    provider: 'Google',
    contextWindow: '1M+ tokens',
    description: 'Ultra-fast, massive context window capable of ingesting entire multi-megabyte codebases.',
  },
  {
    id: 'deepseek/deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    contextWindow: '64k tokens',
    description: 'Specialized coding intelligence with deep syntax and vulnerability analysis.',
  },
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    contextWindow: '128k tokens',
    description: 'Robust multi-modal coding model with dependable instruction following.',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B',
    provider: 'Alibaba',
    contextWindow: '128k tokens',
    description: 'Open-weight coding powerhouse with high accuracy on complex algorithms.',
  },
];

/**
 * Automatically upgrades the Council personas and Synthesizer to high-capability coding models
 */
export function upgradeToHighCapabilityCodingCouncil(
  personas: Persona[],
  synthesizer: Persona
): { updatedPersonas: Persona[]; updatedSynthesizer: Persona } {
  const modelAssignments = [
    'anthropic/claude-3.7-sonnet',
    'deepseek/deepseek-chat',
    'google/gemini-3.7-flash',
    'openai/gpt-4o',
    'qwen/qwen-2.5-72b-instruct',
  ];

  const updatedPersonas = personas.map((p, idx) => ({
    ...p,
    model: modelAssignments[idx % modelAssignments.length],
  }));

  const updatedSynthesizer = {
    ...synthesizer,
    model: 'anthropic/claude-3.7-sonnet',
  };

  return {
    updatedPersonas,
    updatedSynthesizer,
  };
}
